### PR TITLE
Implement xmake generator

### PR DESCRIPTION
**Pull request by waruqi**
Run tests

```console
$ cd conan-xmake_generator
$ conan export . bincrafters/testing
$ cd test_package
$ xmake
```

Run with the verbose info

```console
$ xmake -v
```

Output

```console
ruki:test_package ruki$ xmake
checking for the architecture ... x86_64
checking for the Xcode directory ... /Applications/Xcode.app
checking for the SDK version of Xcode ... 10.14
note: try installing these packages (pass -y to skip confirm)?
  -> CONAN::zlib/1.2.11@conan/stable  (debug)
  -> CONAN::OpenSSL/1.0.2n@conan/stable  
please input: y (y/n)

  => installing CONAN::zlib/1.2.11@conan/stable .. ok
  => installing CONAN::OpenSSL/1.0.2n@conan/stable .. ok

[  0%]: ccache compiling.release src/main.c
[100%]: linking.release test
```

```console
$ xmake -r -v
[  0%]: ccache compiling.release src/main.c
/usr/local/bin/ccache xcrun -sdk macosx clang -c -fvisibility=hidden -O3 -I/Users/ruki/.conan/data/OpenSSL/1.0.2n/conan/stable/package/3986cd17d56fe6657f69f2110b37a2aaa2c15128/include -I/Users/ruki/.conan/data/zlib/1.2.11/conan/stable/package/534dcc368c999e07e81f146b3466b8f656ef1f55/include -I/Users/ruki/.conan/data/zlib/1.2.11/conan/stable/package/1513b3452ef7e2a2dd5f931247c5e02edeb98cc9/include -Qunused-arguments -arch x86_64 -fpascal-strings -fmessage-length=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -o build/.objs/test/macosx/x86_64/release/src/main.c.o src/main.c
[100%]: linking.release test
"xcrun -sdk macosx clang++" -o build/macosx/x86_64/release/test build/.objs/test/macosx/x86_64/release/src/main.c.o -Wl,-x -fvisibility=hidden -L/Users/ruki/.conan/data/OpenSSL/1.0.2n/conan/stable/package/3986cd17d56fe6657f69f2110b37a2aaa2c15128/lib -L/Users/ruki/.conan/data/zlib/1.2.11/conan/stable/package/534dcc368c999e07e81f146b3466b8f656ef1f55/lib -L/Users/ruki/.conan/data/zlib/1.2.11/conan/stable/package/1513b3452ef7e2a2dd5f931247c5e02edeb98cc9/lib -lssl -lcrypto -lz -arch x86_64 -mmacosx-version-min=10.14 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -stdlib=libc++
build ok!👌

```

### CODE REVIEW

**Comment by solvingj** [comment]
This looks really great so far.  

`test_package/conanfile.py` is a Conan convention with special behavior.  When a user runs command: `conan create ...` in the parent directory for the "parent package", Conan will automatically build and run the `test_package` after the "parent package" has been created successfully.  It's purpose is to prove that another Conan project can successfully consume the "parent package". 

In the case of a package like `OpenSSL` or `zlib`, the purpose of `test_package` is to prove that headers and libs are successfully being published and propagated.  

In the case of a generator like this project, the purpose is to prove something related, but different. 

Here, the `test_package` needs to prove that another Conan package which uses `xmake` as it's native build system can do the following: 

1.  list `xmake` as a generator
2.  use the generated `conanbuildinfo.xmake.lua` file in an `xmake` build
3.  find the headers and libs in Conan Cache using this file

For example, in the near future, we want to write a Conan recipe for `tbox` and `gbox`.  To do this, we need to be able to fulfill all 3rd party dependencies for `tbox` and `gbox` using this generator, and have it work inside a Conan recipe (when doing `conan create ...`) .  

So, we'll need to restore the `test package/conanfile.py`, and have it run the same commands we would run to build tbox inside the `conanfile.py`.  For now, I think that would be `self.run("xmake build")`.

**Review by solvingj — COMMENTED** [review]
Looks good, review has been left in the PR discussion.

**Comment by waruqi** [comment]
Ok, I got it. I will restore the test package/conanfile.py.

**Comment by waruqi** [comment]
@solvingj I have restored conanfile.py file

**Pull request merged**
